import { Providers } from "@/lib/providers";
import "./styles/index.scss";
import type { Metadata } from "next";
import { lato, rufina } from "./fonts";
import { MenuComponent } from "../components/General/MenuComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en" className={`${lato.variable} ${rufina.variable}`}>
        <body>
          <MenuComponent />
          {children}
        </body>
      </html>
    </Providers>
  );
}
